export const styles = {
  // -------------------
  // Carrossel
  homeContainer: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    backgroundColor: "#fff",
  },
  navigationIcon: {
     fontFamily: 'Poppins_400Regular',
    width: 20,
    padding:10,
    height: 20,
  },
  iconContainer: {
     fontFamily: 'Poppins_400Regular',
    alignItems: 'center',
    justifyContent: 'center',
    width: 38,
    height: 38,
    borderRadius: 20,
  },
  loadingContainer: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollViewContent: {
     fontFamily: 'Poppins_400Regular',
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  headerContainer: {
     fontFamily: 'Poppins_400Regular',
    alignItems: "center",
    width: "100%",
    marginVertical: 20,
  },

  inicialView: {
     fontFamily: 'Poppins_400Regular',
    flexGrow: 1,
    flex: 1,
    justifyContent: "center",
    paddingTop: 95,
    alignItems: "center",
  },
  Container: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  dashView: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  image: {
     fontFamily: 'Poppins_400Regular',
    width: 300,
    height: 300,
    resizeMode: "contain",
  },
  buttonCircle: {
     fontFamily: 'Poppins_400Regular',
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "100%",
  },
  titleText: {
     fontFamily: 'Poppins_400Regular',
    color: "#361F08",
    fontSize: 24,
    margin: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
  descriptionText: {
     fontFamily: 'Poppins_400Regular',
    color: "#361F08",
    fontSize: 16,
    textAlign: "center",
    width: "75%",
  },
  // -------------------
  safeAreaView: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
  },
  tittle: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 18,
    padding: 1,
    fontWeight: "600",
    color: "#fff",
  },
  tittleDark: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 20,
    padding: 10,
    fontWeight: "600",
    color: "#000",
  },
  txt: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 15,
    color: "#000",
  },
  txtBtn: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: "#fff",
  },
  input: {
     fontFamily: 'Poppins_400Regular',
    borderBottomWidth: 1,
    borderColor: "#ccc",
    padding: 10,
    width: 200,
  },
  enterBtn: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "row",
    width: 120,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#361F08",
    color: "#fff",
    borderRadius: 5,
    marginTop: 20,
  },
  // ------------------------------------
  // Inicial START
  // ------------------------------------
  navBtn: {
     fontFamily: 'Poppins_400Regular',
    display: "flex",
    marginTop: 30,
    width: "45%",
    flexDirection: "row",
    justifyContent: "center",
    aligneItens: "center",
    justifyContent: "space-around",
  },
  activeBtn: {
     fontFamily: 'Poppins_400Regular',
    width: 40,
    height: 40,
    borderRadius: "100%",
    backgroundColor: "#AAC095",
  },
  initialBtn: {
     fontFamily: 'Poppins_400Regular',
    width: 40,
    height: 40,
    borderRadius: "100%",
    borderWidth: 2,
    borderColor: "#2D465C",
  },

  // ------------------------------------
  // Inicial END
  // ------------------------------------
  // ------------------------------------
  // Home START
  // ------------------------------------
  header: {
     fontFamily: 'Poppins_400Regular',
    justifyContent: "center",
    padding: 20,
    flexDirection: "row",
  },
  headerItem: {
     fontFamily: 'Poppins_400Regular',
    justifyContent: "center",
    flexDirection: "column",
    marginLeft: 20,
    borderWidth: 0,
    marginRight: -70,
  },
  // ------------------------------------
  banners: {
     fontFamily: 'Poppins_400Regular',
    width: "100%",
    height: 150,
    justifyContent: "center",
    alignItems: "center",
    backgroundImage: "url('../assets/img/background/home.png')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    borderRadius: 20,
  },
  bannerItem: {
     fontFamily: 'Poppins_400Regular',
    width: 220,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    flexDirection: "column",
    border: "none",
    borderRadius: 10,
    backgroundColor: "#fff",
  },
  bannerText: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 19,
    fontWeight: "800",
  },
  bannerSubText: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 11,
  },
  // ------------------------------------
  buttons: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTittle: {
     fontFamily: 'Poppins_400Regular',
    color: "#fff",
    fontSize: 23,
    fontWeight: "600",
  },
  buttonText: {
     fontFamily: 'Poppins_400Regular',
    color: "#fff",
    fontSize: 12,
    fontWeight: "0",
  },
  buttonItem: {
     fontFamily: 'Poppins_400Regular',
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 50,
    marginBottom: 20,
    textAlign: "left",
    marginRight: 100,
    width: 300,
    height: 100,
    borderRadius: 15,
    padding: 15,
    backgroundColor: "#C1959D",
  },
  buttonBar: {
     fontFamily: 'Poppins_400Regular',
    width: 30,
    position: "relative",
    left: "5%",
    height: 100,
    backgroundColor: "rgb(158, 97, 108)",
    borderRadius: 12,
  },
  // ------------------------------------
  buttonContent: {
     fontFamily: 'Poppins_400Regular',
    marginLeft: 25,
  },
  buttonItem2: {
     fontFamily: 'Poppins_400Regular',
    alignItems: "center",
    flexDirection: "row",
    textAlign: "left",
    marginRight: -90,
    width: 300,
    height: 100,
    borderRadius: 15,
    padding: 15,
    backgroundColor: "#90A293",
  },
  buttonBar2: {
     fontFamily: 'Poppins_400Regular',
    width: 30,
    position: "relative",
    right: "84%",
    height: 100,
    backgroundColor: "#3F4D42",
    borderRadius: 12,
  },
  // ------------------------------------
  buttonItem3: {
     fontFamily: 'Poppins_400Regular',
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 20,
    marginBottom: 50,
    textAlign: "left",
    marginRight: 100,
    width: 300,
    height: 100,
    borderRadius: 15,
    padding: 15,
    backgroundColor: "#462F19",
  },
  buttonBar3: {
     fontFamily: 'Poppins_400Regular',
    width: 30,
    position: "relative",
    left: "10%",
    height: 100,
    backgroundColor: "#654728",
    borderRadius: 12,
  },
  // ------------------------------------
  footer: {
     fontFamily: 'Poppins_400Regular',
    display: "flex",
    justifyContent: "center",
    justifyContent: "space-Around",
    alignItems: "center",
    margin: 50,
    width: 200,
    height: 100,
  },
  footerItem: {
     fontFamily: 'Poppins_400Regular',
    marginBottom: 55,
  },

  // ------------------------------------
  // Home END
  // ------------------------------------
  // ------------------------------------
  // Area Aluno START
  // ------------------------------------
  btnAreaAluno: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "row",
    alignItems: "center",
    marginTop: 50,
    color: '#000',
    borderRadius: 20,
    backgroundColor: '#f1f1f1',
    borderWidth: 3,
    borderColor: "#D8D8D8",
    shadowColor: "rgba(6, 51, 54, 0.1)",
    shadowOffset: { width: 0, height: 2 },
    margin: 10,
    position: "relative",
    bottom: -96,
    padding: 7,
  },
  personAreaAluno: {
     fontFamily: 'Poppins_400Regular',
    width: 130,
    height: 180,
    elevation: 10,
    position: "absolute",
    left: -20,
    top: -94,
  },

  receita: {
    fontFamily: 'Poppins_400Regular',
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    padding: 12,
    marginBottom: 15,
    width: "100%",
    justifyContent: "space-around", 
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D8D8D8",
    shadowColor: "rgba(6, 51, 54, 0.1)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 16,
    elevation: 5, 
    borderRadius: 16,
  },
  infoReceita:{
    width: 160,
    flexDirection: 'row',
    justifyContent: 'center',
    justifyContent:  'space-around',
    alignSelf: 'flex-start',
    padding:5,
  },
  itemReceita:{
    flexDirection: 'column',
  },
  receitaTittle: {
    fontFamily: 'Poppins_400Regular',
   fontSize: 15,
   fontWeight: "700",
   width: 140,
   textAlign: "left",
 },
  imgReceita: {
     fontFamily: 'Poppins_400Regular',
    width: 120,
    height: 110,
    borderRadius: 28,
  },
  textContainer: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    padding: 8,
    marginLeft: 113,
  },
  titleReceita: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: "#000",
    fontWeight: "bold",
  },
  
  subtitleReceita: {
    fontFamily: 'Poppins_400Regular',
   color: "#000",
   fontSize: 12,
   marginTop: 5,
 },
  btnReceita: {
    fontFamily: 'Poppins_400Regular',
   flexDirection: "row",
   alignItems: "center",
   justifyContent: 'center',
   padding: '5px',
   backgroundColor: "#042628",
   width: 30,
   borderRadius: 8,
 },
  subtitle: {
     fontFamily: 'Poppins_400Regular',
    color: "#fff",
    fontSize: 12,
    marginTop: 5,
  },
  buttonText: {
     fontFamily: 'Poppins_400Regular',
    color: "#fff",
    textAlign: "center",
  },
  // ------------------------------------
  // Area END
  // ------------------------------------
  // ------------------------------------
  // Cursos START
  // ------------------------------------
  ContCurso: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  cursoTittle: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 15,
    fontWeight: "700",
    textAlign: "left",
  },
  cursoImage: {
     fontFamily: 'Poppins_400Regular',
    width: 100,
    height: 100,
    borderRadius: 20,
  },
  cursoText: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    textAlign: "left",
  },
  btnCursoUm: {
     fontFamily: 'Poppins_400Regular',
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    textAlign: "center",
    marginTop: 10,
    padding: 3,
    backgroundColor: "#3F4D42",
    color: "#fff",
    borderRadius: 15,
  },
  btnCursoDois: {
     fontFamily: 'Poppins_400Regular',
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    textAlign: "center",
    marginTop: 10,
    padding: 3,
    backgroundColor: "#9E616C",
    color: "#fff",
    borderRadius: 15,
  },

  tabnone: {
     fontFamily: 'Poppins_400Regular',
    display: "none",
  },

  // ------------------------------------
  // Descrisção Curso START
  // ------------------------------------
  containerCurso: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "row",
    marginTop: 20,
    padding: 15,
    borderWidth: 1,
    borderColor: "#D8D8D8",
    shadowColor: "rgba(6, 51, 54, 0.1)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 16,
  },
  descriContainer: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "column",
    padding: 10,
    alignItems: "center",
    justifyContent: "space-Around",
  },
  infoCursos: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    padding: 10,
    flexDirection: "column",
    alignSelf: "flex-Start",
  },
  btnCurso: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 10,
  },
  titleCurso: {
     fontFamily: 'Poppins_400Regular',
    fontWeight: "700",
    fontSize: 15,
    padding: 5,
  },
  txtCurso: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    textAlign: "left",
    width: 205,
  },

  // ------------------------------------
  // Cursos END
  // ------------------------------------
  // ------------------------------------
  // Produtos START
  // ------------------------------------
  produtos: {
     fontFamily: 'Poppins_400Regular',
    marginTop: 50,
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-evenly",
  },
  contProdutos: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    justifyContent: "space-Around",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D8D8D8",
    shadowColor: "rgba(6, 51, 54, 0.1)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 16,
  },
  produtoBtn: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    flexDirection: "row",
    width: 155,
    alignItems: "center",
    padding: 10,
  },
  produtoItem: {
     fontFamily: 'Poppins_400Regular',
    width: 200,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: {
       fontFamily: 'Poppins_400Regular',
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },

  contProdutos: {
     fontFamily: 'Poppins_400Regular',
    alignItems: "center",
    borderRadius: 20,
    justifyContent: "flex-start",
  },
  produtoItem: {
     fontFamily: 'Poppins_400Regular',
    // width: '80%',
    backgroundColor: "#fff",
    borderRadius: 10,
    // padding: 10,
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
  },
  produtoBtn: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 145,
    marginTop: 10,
  },
  modalView: {
     fontFamily: 'Poppins_400Regular',
    width: 330,
    padding: 20,
    backgroundColor: "white",
    borderRadius: 10,
    alignItems: "center",
    shadowColor: "rgba(0, 0, 0, 0.2)",
    shadowOffset: {
       fontFamily: 'Poppins_400Regular',
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    borderColor: "rgba(112, 112, 112, 0.3)",
    borderWidth: 1,
  },
  modalDescription: {
     fontFamily: 'Poppins_400Regular',
    marginTop: 10,
    fontSize: 14,
    textAlign: "center",
  },
  closeButton: {
     fontFamily: 'Poppins_400Regular',
    marginTop: 20,
    padding: 10,
    backgroundColor: "#2196F3",
    borderRadius: 5,
  },
  closeButtonText: {
     fontFamily: 'Poppins_400Regular',
    color: "white",
    fontWeight: "bold",
  },
  btnItem: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "row",
    alignItems: "center",
    justifyContent: 'center',
    padding: '5px',
    backgroundColor: "#A2845E",
    width: 30,
    borderRadius: 8,
  },
  centeredView: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.1)",
  },
  // modalView: {
   fontFamily: 'Poppins_400Regular',
  //   backgroundColor: "#fff",
  //   borderRadius: 10,
  //   padding: 20,
  //   alignItems: "center",
  //   elevation: 5,
  // },
  modalText: {
     fontFamily: 'Poppins_400Regular',
    fontWeight: "bold",
    fontSize: 18,
    margin: 10,
  },

  textStyle: {
     fontFamily: 'Poppins_400Regular',
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },

  // ------------------------------------
  // Produtos END
  // ------------------------------------
  // ------------------------------------
  // Aula START
  // ------------------------------------
  aulaImage: {
     fontFamily: 'Poppins_400Regular',
    width: 60,
    height: 60,
    borderRadius: 10,
  },
  aula: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    padding: 12,
    marginBottom: 15,
    width: "22em",
    justifyContent: "space-Around",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#D8D8D8",
    shadowColor: "rgba(6, 51, 54, 0.1)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 16,
  },
  contAula: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    marginTop: 30,
    justifyContent: "space-Around",
    alignItems: "center",
  },
  videoContainer: {
     fontFamily: 'Poppins_400Regular',
    width: 340,
    height: 240,
    borderRadius: 10,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  Video: {
     fontFamily: 'Poppins_400Regular',
    width: 340,
    height: 240,
    borderRadius: 25,
    borderWidth: 4,
    borderColor: "#3F4D42",
  },
  // ------------------------------------
  // Aula end
  // ------------------------------------
  // ------------------------------------
  // Perfil START
  // ------------------------------------
  profile: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "column",
  },
  perfilImage: {
     fontFamily: 'Poppins_400Regular',
    width: 100,
    height: 100,
    borderRadius: 100,
  },
  btnEditPerfil: {
     fontFamily: 'Poppins_400Regular',
    justifyContent:' center',
    alignItems:' center' ,
    width: '19em',
    height:' 2.4em',
    textAlign:' center',
    margin:' 33px',
    padding: '3px',
    backgroundColor: 'rgb(63, 77, 66)',
    color: 'rgb(255, 255, 255)',
    borderRadius:' 5px',
  },
  textperfil: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "column",
    textAlign: "center",
    padding: 2,
  },
  toptextPerfil:{
    fontWeight: "700",
    marginTop: 14 ,
  },
  perfiltittle: {
     fontFamily: 'Poppins_400Regular',
    textAlign: "center",
    fontSize: 14,
    padding: 1,
    fontWeight: "600",
    color: "#fff",
  },
  perfilText: {
     fontFamily: 'Poppins_400Regular',
    textAlign: "center",
    color: "#fff",
    fontSize: 12,
    fontWeight: "0",
  },
  perfilDados: {
     fontFamily: 'Poppins_400Regular',
    marginTop: 50,
    backgroundColor: "#462F19",
    color: "#fff",
    justifyContent: "center",
    justifyContent: "space-evenly",
    flexDirection: "row",
    borderBottomWidth: 4,
    borderColor: "#382513",
    borderRadius: 12,
    padding: 5,
  },
  headerEdit: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    textAlign: "left",
    marginTop: 95,
    justifyContent: "center",
    alignItems: "center",
    height: 100,
  },
  ContainerPerfil: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    textAlign: "left",
    marginTop: 20,
    justifyContent: "center",
    alignItems: "center",
    height: 100,
  },
  inputPerfil: {
    borderWidth: 1,
    borderColor: "#D8D8D8",
    shadowColor: "rgba(6, 51, 54, 0.1)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 16,
     fontFamily: 'Poppins_400Regular',
    borderWidth: 1,
    textAlign: "left",
    borderRadius: 15,
    borderColor: "#ccc",
    padding: 10,
    width: 280,
  },
  textInfoPerfil: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: 'row',
    width: "100%",
    justifyContent: 'space-between',
    alignItems: 'center',           
    textAlign: "left",
    padding: 3,
  },
  
  contInfo: {
     fontFamily: 'Poppins_400Regular',
    justifyContent: 'space-around',
    textAlign: "left",
    padding: 10,
    borderWidth: 1,
    borderColor: '#F6F6F6',
    width: "80%",
  },

  // ------------------------------------
  // Perfil END
  // ------------------------------------
  imgFundoSenha: {
     fontFamily: 'Poppins_400Regular',
    width: "100%",
    height: 280,
  },
  enterBtnSenha: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "row",
    width: 120,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#361F08",
    color: "#fff",
    borderRadius: 5,
    margin: 20,
  },

  // ------------------------------------
  // Notificacao Start
  // ------------------------------------
  ContainerNotificacao: {
     fontFamily: 'Poppins_400Regular',
    justifyContent: "center",
    alignItems: "center",
    margin: 15,
  },

  InputNotificacao: {
     fontFamily: 'Poppins_400Regular',
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#707070",
    color: "#fff",
    width: 360,
    padding: 15,
    borderRadius: 15,
    borderLeftWidth: 11,
    borderLeftColor: "#3F4D42",
    borderWidth: 1,
    borderColor: "#D8D8D8",
    shadowColor: "rgba(6, 51, 54, 0.1)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 16,
  },

  iconNotificacao: {
     fontFamily: 'Poppins_400Regular',
    width: 30,
    height: 30,
  },

  itemNotificacao: {
     fontFamily: 'Poppins_400Regular',
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 10,
  },

  contMsg: {
     fontFamily: 'Poppins_400Regular',
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-start",
  },

  tituloNotificacao: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 15,
    fontWeight: "bold",
    marginBottom: 5,
  },

  mensagemNotificacao: {
     fontFamily: 'Poppins_400Regular',
    fontSize: 13,
  },

  // ------------------------------------
  // Notificacao END
  // ------------------------------------
};
